### ISSUE TITLE
mod_strips doesn't work on OSX 10.8.5

### ISSUE THREAD

**Issue by qq99** [spolu/breach_core#58]
github  mod_strip   v0.2.8-alpha.5  breach  v0.2.8-alpha.5   stopped     up to date

```
Error: Cannot find module 'utils-merge'
    at Function.Module._resolveFilename (module.js:331:15)
    at Function.Module._load (module.js:273:25)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at Object.<anonymous> (/Users/anthony/Library/Application Support/breach/modules/breach/mod_strip#v0.2.8-alpha.5/node_modules/express/lib/express.js:6:13)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Module.require (module.js:357:17)
OPTION: --no-chrome
module.js:333
    throw err;
          ^
```

here's the output I see from `mod_strip`

Breach also crashed after trying to install `mod_strip` in the onboarding

**Comment by spolu** [comment]
Hi @qq99 Thanks for reporting that.

I would say that your npm install didn't work. You can try to remove the module and reinstall it.
If it does not solve your issue you can also delete entirely `~/Library/Application Support/breach` and relaunch breach.

Please let me know if this solves the issue!

**Comment by qq99** [comment]
Yep, that was it!  Remove and re-add with the input down below worked

**Comment by spolu** [comment]
Sweet!

**Comment by paulmwatson** [comment]
If it helps I had this issue and just had to update npm and node, had old versions. I also had to npm install debug and npm install isarray to get mod_strip working.

**Comment by spolu** [comment]
This may be related to some env vars you had due to old version of npm/node ?
